apiVersion: v1
kind: Service
metadata:
  name: entry-service
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: entry-ingress
  namespace: default
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: entry-service
          servicePort: http
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: entry-route-search
  namespace: default
spec:
  destination:
    name: entry-service
    namespace: default
  match:
    request:
      headers:
        uri:
          prefix: "/search"
  rewrite:
    authority: search-service-route.default.demo-domain.com
  route:
  - destination:
      name: istio-ingress
      namespace: istio-system
    weight: 100
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: entry-route-login
  namespace: default
spec:
  destination:
    name: entry-service
    namespace: default
  match:
    request:
      headers:
        uri:
          prefix: "/login"
  rewrite:
    authority: login-service-route.default.demo-domain.com
  route:
  - destination:
      name: istio-ingress
      namespace: istio-system
    weight: 100
